### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by chryton** [WebDevSummit/random-recipes#1]
## PHP
- [x] Namespace
- [x] Add configuration block
- [x] Add comments
- [x] Modularize API call strings
## CSS
- [x] Convert CSS to something sexier like SASS/LESS
- [x] Add comments
- [x] Fix spacing to be consistant
## Misc.
- [x] Create sexier readme
- [x] Make sexier overall

**Comment by ericnkatz** [comment]
@johnbhartley if you wanted to play around with this some more you could rewrite it to utilize something like this: https://github.com/cdaguerre/php-trello-api
